### PR TITLE
replace Proptypes with prop-types

### LINKED ISSUE #11: use prop-types package instead of React.PropTypes.

### PR DESCRIPTION
**Pull request by ritz078**
closes #11

### CODE REVIEW

**Comment by ritz078** [comment]
@1egoman  Any update on this ?

**Comment by 1egoman** [comment]
Oops, sorry! Didn't see this PR.

**Review by 1egoman — APPROVED** [review]

**Comment by ritz078** [comment]
can you make a new release ?

**Comment by 1egoman** [comment]
Just published `react-fuzzy-picker@0.6.0` off of `1a63889`.

**Pull request merged**
